import asyncpg
import os

_pool: asyncpg.Pool | None = None


async def init_db():
    global _pool

    if _pool:
        return

    _pool = await asyncpg.create_pool(
        host=os.getenv("DB_HOST"),
        port=int(os.getenv("DB_PORT", 5432)),
        database=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        min_size=1,
        max_size=10
    )


async def close_db():
    global _pool
    if _pool:
        await _pool.close()
        _pool = None


def get_pool() -> asyncpg.Pool:
    if not _pool:
        raise RuntimeError("Database not initialized")
    return _pool


# ===== helper functions =====

async def fetch(query: str, *args):
    pool = get_pool()
    async with pool.acquire() as conn:
        return await conn.fetch(query, *args)


async def fetchrow(query: str, *args):
    pool = get_pool()
    async with pool.acquire() as conn:
        return await conn.fetchrow(query, *args)


async def execute(query: str, *args):
    pool = get_pool()
    async with pool.acquire() as conn:
        return await conn.execute(query, *args)


async def executemany(query: str, args_list):
    pool = get_pool()
    async with pool.acquire() as conn:
        return await conn.executemany(query, args_list)

import json

async def get_setup_session(user_id: int, guild_id: int):
    return await fetchrow(
        "SELECT step, data FROM ticket_setup_sessions WHERE user_id=$1 AND guild_id=$2",
        user_id, guild_id
    )

async def upsert_setup_session(user_id: int, guild_id: int, step: int, data: dict):
    await execute(
        """
        INSERT INTO ticket_setup_sessions (user_id, guild_id, step, data)
        VALUES ($1, $2, $3, $4)
        ON CONFLICT (user_id, guild_id)
        DO UPDATE SET
            step = EXCLUDED.step,
            data = EXCLUDED.data,
            updated_at = NOW()
        """,
        user_id, guild_id, step, json.dumps(data)
    )

async def delete_setup_session(user_id: int, guild_id: int):
    await execute(
        "DELETE FROM ticket_setup_sessions WHERE user_id=$1 AND guild_id=$2",
        user_id, guild_id
    )

# add to core/database.py

async def init_schema():
    """Create required tables if they don't exist"""

    queries = [
        """
        CREATE TABLE IF NOT EXISTS ticket_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,

    title TEXT NOT NULL,
    name TEXT NOT NULL,
    auto_close_after INTERVAL
    );
""",

        """CREATE TABLE IF NOT EXISTS ticket_category_support_roles (
    category_id INTEGER NOT NULL REFERENCES ticket_categories(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL,

    PRIMARY KEY (category_id, role_id)
);""",
        """CREATE TABLE IF NOT EXISTS ticket_category_channel_config (
    category_id INTEGER PRIMARY KEY REFERENCES ticket_categories(id) ON DELETE CASCADE,
    discord_category_id BIGINT NOT NULL
);""", """CREATE TABLE IF NOT EXISTS ticket_category_thread_config (
            category_id INTEGER PRIMARY KEY REFERENCES ticket_categories(id) ON DELETE CASCADE,
            parent_channel_id BIGINT NOT NULL
        );""",
        """
CREATE TABLE IF NOT EXISTS ticket_panels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    message_id BIGINT,
    panel_name TEXT,           -- user-friendly name
    is_active BOOLEAN DEFAULT TRUE,

    content TEXT,          -- plain message content (this is the text outside the embed)
    embed JSONB,           -- full embed structure (has title,desc,image, whatnot)

    component_type TEXT NOT NULL CHECK (component_type IN ('buttons', 'select')),
    ticket_mode TEXT NOT NULL CHECK (ticket_mode IN ('channel', 'thread')),
    UNIQUE (channel_id, message_id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
        """,
        """
        CREATE TABLE IF NOT EXISTS ticket_panel_buttons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_id INT NOT NULL REFERENCES ticket_panels(id) ON DELETE CASCADE,

    label TEXT NOT NULL,
    style INT NOT NULL,
    emoji TEXT,
    position INTEGER NOT NULL,
    UNIQUE (panel_id, position),

    category_id INTEGER NOT NULL REFERENCES ticket_categories(id) ON DELETE CASCADE
);
""",
        """
        CREATE TABLE IF NOT EXISTS ticket_panel_selects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_id INT NOT NULL REFERENCES ticket_panels(id) ON DELETE CASCADE,

    label TEXT NOT NULL,
    description TEXT,
    emoji TEXT,
    position INTEGER NOT NULL,
    UNIQUE (panel_id, position),
    category_id INTEGER NOT NULL REFERENCES ticket_categories(id) ON DELETE CASCADE
);
""",
    "CREATE INDEX IF NOT EXISTS idx_panels_guild ON ticket_panels(guild_id);",
    "CREATE INDEX IF NOT EXISTS idx_categories_guild ON ticket_categories(guild_id);",
    "CREATE INDEX IF NOT EXISTS idx_buttons_panel ON ticket_panel_buttons(panel_id);",
    "CREATE INDEX IF NOT EXISTS idx_selects_panel ON ticket_panel_selects(panel_id);",

    """
CREATE UNIQUE INDEX unique_unsent_panel_per_channel ON ticket_panels(channel_id) WHERE message_id IS NULL;""",
        "CREATE INDEX IF NOT EXISTS idx_buttons_category ON ticket_panel_buttons(category_id);",
        "CREATE INDEX IF NOT EXISTS idx_selects_category ON ticket_panel_selects(category_id);",
        "CREATE INDEX IF NOT EXISTS idx_panels_channel ON ticket_panels(channel_id);",
        "CREATE INDEX IF NOT EXISTS idx_support_roles_role ON ticket_category_support_roles(role_id);",
        """
CREATE TABLE IF NOT EXISTS ticket_setup_sessions (
    user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,

    step INTEGER NOT NULL,
    data JSONB NOT NULL DEFAULT '{}',

    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    PRIMARY KEY (user_id, guild_id)
);
"""
    ]

    pool = get_pool()
    async with pool.acquire() as conn:
        async with conn.transaction():
            for q in queries:
                await conn.execute(q)
